import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/provider/theme-provider";
import { Header } from "@/components/header";
import { Toaster } from "sonner";
import { AuthProvider } from "@/provider/user-provider";
import Providers from "@/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          <div className="container mx-auto mt-32 md:mt-16">{children}</div>
        </Providers>

        <Toaster position="top-center" />
      </body>
    </html>
  );
}
